services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=codegroup'
      - 'POSTGRES_USER=codegroup'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - '5432:5432'
volumes:
  postgres_volume: {}
