services:
  ci_sonar:
    image: sonarqube:lts-community
    container_name: ci_sonar
    ports:
      - "9000:9000"
    networks:
      - ci
  app_db:
    image: 'postgres:latest'
    container_name: app_db
    command: >
      -c 'listen_addresses=*'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - 'POSTGRES_DB=codegroup'
      - 'POSTGRES_USER=codegroup'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - "5434:5432"
    networks:
      - app    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codegroup"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  ci:
    name: ci_network
  app:
    name: app_network
