server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:codegroup}
    username: ${DB_USERNAME:codegroup}
    password: ${DB_PASSWORD:123456}
    initialization-mode: always
    connectionTestQuery: 'SELECT 1'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: validate
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always